spring.application.name=senac
spring.datasource.url=jdbc:postgresql://localhost/senac
spring.datasource.username=postgres
spring.datasource.password=Sen@c2023
spring.datasource.driver-class-name=org.postgresql.Driver
hibernate.dialect=org.hibernate.dialect.HSQLDialect

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=senacprojeto2026@gmail.com
spring.mail.password=hruw larr rljl fjfs
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

api.frontend.base-url=http://localhost:5173

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.secretkey="wdihwaudiwadwau"
spring.tempo_expiracao=15


cloudinary.cloud-name=dyw8jwpix
cloudinary.api-key=859795256817611
cloudinary.api-secret=JztUtU9aWHFcPYP2EtB9xche4c4

resilience4j.circuitbreaker.instances.imagemStorage.sliding-window-size=3
resilience4j.circuitbreaker.instances.imagemStorage.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.imagemStorage.wait-duration-in-open-state=30s